macOS-related fixes to the installer
beefproject/beef pull request #2107
Opened 2021-05-29 23:10 UTC by gmerlino

The installer does not work otherwise, at least under (recent) macOS versions

2021-09-07 00:30 UTC, wheatley commented
@gmerlino thanks for the PR
we're looking at pushing this into our next release and was wondering if you'd like to join our discord?

2021-09-08 08:26 UTC, jackwalker-ripmfa commented
@wheatley - should link to Discord in README where the other links to external BeEF resources are.

2021-09-10 01:27 UTC, DeezyE requested changes
thanks gmerlino, see my comments

2021-09-10 01:29 UTC, wheatley reviewed
added some comments for review
we'll be pushing this PR to the next release

2021-09-10 01:29 UTC, wheatley commented on .bundle/config
> -BUNDLE_WITH: "test:tests"
this needs to be removed due to release version 0.5.1.0 updating this file

2021-10-19 02:21 UTC, DeezyE commented
@gmerlino are you available to address the above issues?

2021-11-09 05:16 UTC, wheatley commented
Closing due to inactivity.

2021-11-09 05:16 UTC, closed without merging